/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormidospizza;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Ana Marta
 */
public class AdminiPizza extends javax.swing.JFrame {
    
    ArrayList<Pizzas> Listado2; 
    ArrayList<Ordenes> Listado; 
    
    public AdminiPizza(ArrayList<Pizzas> listado1, ArrayList<Ordenes> listado2 ) {
        Listado2=listado1;
        Listado=listado2;
        initComponents();
        //Centrar el Jframe
        this.setLocationRelativeTo(null);
        
        //Fondo para el JFrame
        this.getContentPane().setBackground(Color.WHITE);
        VerLista ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombrePizzeria = new javax.swing.JLabel();
        Sucursal = new javax.swing.JLabel();
        SeleccionSucursal = new javax.swing.JComboBox<>();
        Pizzas = new javax.swing.JLabel();
        Nombrepizzas = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        PrecioPizzas = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        botoncrear = new javax.swing.JButton();
        Descripcionpizza = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPizza = new javax.swing.JTable();
        botonregresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombrePizzeria.setBackground(new java.awt.Color(255, 255, 255));
        NombrePizzeria.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        NombrePizzeria.setForeground(new java.awt.Color(204, 0, 0));
        NombrePizzeria.setText("Dormidos Pizza");

        Sucursal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Sucursal.setForeground(new java.awt.Color(0, 0, 153));
        Sucursal.setText("Sucursal");

        SeleccionSucursal.setBackground(new java.awt.Color(204, 204, 255));
        SeleccionSucursal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SeleccionSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala ", "El progreso", "Jalapa" }));
        SeleccionSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionSucursalActionPerformed(evt);
            }
        });

        Pizzas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Pizzas.setForeground(new java.awt.Color(204, 0, 0));
        Pizzas.setText("Pizzas");

        Nombrepizzas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Nombrepizzas.setForeground(new java.awt.Color(0, 0, 153));
        Nombrepizzas.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        PrecioPizzas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        PrecioPizzas.setForeground(new java.awt.Color(0, 0, 153));
        PrecioPizzas.setText("Precio");

        txtPrecio.setBackground(new java.awt.Color(204, 204, 255));
        txtPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 255));
        txtDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        botoncrear.setBackground(new java.awt.Color(204, 0, 0));
        botoncrear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botoncrear.setForeground(new java.awt.Color(255, 255, 255));
        botoncrear.setText("Crear");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });

        Descripcionpizza.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Descripcionpizza.setForeground(new java.awt.Color(0, 0, 153));
        Descripcionpizza.setText("Descripción");

        tablaPizza.setBackground(new java.awt.Color(204, 204, 255));
        tablaPizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaPizza.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tablaPizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion ", "Precio"
            }
        ));
        tablaPizza.setGridColor(new java.awt.Color(0, 0, 0));
        tablaPizza.setRowHeight(25);
        jScrollPane1.setViewportView(tablaPizza);

        botonregresar1.setBackground(new java.awt.Color(204, 0, 0));
        botonregresar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonregresar1.setForeground(new java.awt.Color(255, 255, 255));
        botonregresar1.setText("Regresar");
        botonregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nombrepizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeleccionSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(PrecioPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NombrePizzeria)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Descripcionpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Pizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NombrePizzeria)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeleccionSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(Pizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Nombrepizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcionpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(botonregresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionSucursalActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void botonregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregresar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        index i = new index(Listado2, Listado);
        i.setVisible(true);
    }//GEN-LAST:event_botonregresar1ActionPerformed

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        Pizzas pizzas = new Pizzas(txtNombre.getText(), txtPrecio.getText(), txtDescripcion.getText());
        Listado2.add(pizzas);
        VerLista();
    }//GEN-LAST:event_botoncrearActionPerformed
    //Mostar matriz
    public void VerLista (){
        String matriz[][]= new String [Listado2.size()][3];
        for (int i = 0; i < Listado2.size(); i++) {
            matriz [i][0]= Listado2.get(i).getNombre();
            matriz [i][1]= Listado2.get(i).getPrecio();
            matriz [i][2]= Listado2.get(i).getDescripcion();
            
        }
        tablaPizza.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
            new String [] {
                "Nombre", "Descripcion ", "Precio"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminiPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminiPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminiPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminiPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminiPizza().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcionpizza;
    private javax.swing.JLabel NombrePizzeria;
    private javax.swing.JLabel Nombrepizzas;
    private javax.swing.JLabel Pizzas;
    private javax.swing.JLabel PrecioPizzas;
    private javax.swing.JComboBox<String> SeleccionSucursal;
    private javax.swing.JLabel Sucursal;
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botonregresar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPizza;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void Mostrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
