/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormidospizza;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana Marta
 */
    


public class OrdenesPizzas extends javax.swing.JFrame {
    ArrayList<Pizzas> Listado2; 
    ArrayList<Ordenes> Listado; 
    
   // ArrayList<Ordenes> Listado = new ArrayList<Ordenes>();

        public OrdenesPizzas(ArrayList<Pizzas> listado1, ArrayList<Ordenes> listado2) {
        Listado2=listado1;
        Listado=listado2;
        initComponents();
        //Centrar el Jframe
        this.setLocationRelativeTo(null);
        
        //Fondo para el JFrame
        this.getContentPane().setBackground(Color.WHITE);
        SelecPizza.removeAllItems();
        for(int i=0;i<Listado2.size();i++){
           SelecPizza.addItem(Listado2.get(i).getNombre());
        }
        MostarOrden();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescripcionpizzaOrdenes = new javax.swing.JLabel();
        txtPrecios = new javax.swing.JTextField();
        botoncrear = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        txtDescrip = new javax.swing.JTextField();
        PrecioPizzaOrdenes = new javax.swing.JLabel();
        SelecPizza = new javax.swing.JComboBox<>();
        NombredelaPizzaOrdenes = new javax.swing.JLabel();
        NombrePizzeria = new javax.swing.JLabel();
        SucursalOrdenes = new javax.swing.JLabel();
        PrecioPizzaOrdenes1 = new javax.swing.JLabel();
        SelecSucursal = new javax.swing.JComboBox<>();
        txtNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DescripcionpizzaOrdenes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        DescripcionpizzaOrdenes.setForeground(new java.awt.Color(0, 0, 153));
        DescripcionpizzaOrdenes.setText("Descripción");

        txtPrecios.setBackground(new java.awt.Color(204, 204, 255));
        txtPrecios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreciosActionPerformed(evt);
            }
        });

        botoncrear.setBackground(new java.awt.Color(204, 0, 0));
        botoncrear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botoncrear.setForeground(new java.awt.Color(255, 255, 255));
        botoncrear.setText("Ordenar");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });

        btnRegreso.setBackground(new java.awt.Color(204, 0, 0));
        btnRegreso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnRegreso.setForeground(new java.awt.Color(255, 255, 255));
        btnRegreso.setText("Regresar");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        txtDescrip.setBackground(new java.awt.Color(204, 204, 255));
        txtDescrip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        PrecioPizzaOrdenes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        PrecioPizzaOrdenes.setForeground(new java.awt.Color(0, 0, 153));
        PrecioPizzaOrdenes.setText("Precio");

        SelecPizza.setBackground(new java.awt.Color(204, 204, 255));
        SelecPizza.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelecPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delux", "Hawaiiana", "5 carnes", "Chapina" }));
        SelecPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecPizzaActionPerformed(evt);
            }
        });

        NombredelaPizzaOrdenes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        NombredelaPizzaOrdenes.setForeground(new java.awt.Color(0, 0, 153));
        NombredelaPizzaOrdenes.setText("Pizza");

        NombrePizzeria.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        NombrePizzeria.setForeground(new java.awt.Color(204, 0, 0));
        NombrePizzeria.setText("Dormidos Pizza");

        SucursalOrdenes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        SucursalOrdenes.setForeground(new java.awt.Color(0, 0, 153));
        SucursalOrdenes.setText("Sucursal");

        PrecioPizzaOrdenes1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        PrecioPizzaOrdenes1.setForeground(new java.awt.Color(0, 0, 153));
        PrecioPizzaOrdenes1.setText("No. de Orden");

        SelecSucursal.setBackground(new java.awt.Color(204, 204, 255));
        SelecSucursal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelecSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala ", "El progreso", "Jalapa" }));
        SelecSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecSucursalActionPerformed(evt);
            }
        });

        txtNo.setBackground(new java.awt.Color(204, 204, 255));
        txtNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        Tabla1.setBackground(new java.awt.Color(204, 204, 255));
        Tabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Especialidad de la Pizza", "Descripción", "Sucursal"
            }
        ));
        Tabla1.setGridColor(new java.awt.Color(0, 0, 0));
        Tabla1.setRowHeight(25);
        jScrollPane1.setViewportView(Tabla1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DescripcionpizzaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(SelecSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(NombredelaPizzaOrdenes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(SucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(SelecPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(txtPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(PrecioPizzaOrdenes))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(PrecioPizzaOrdenes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NombrePizzeria)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NombrePizzeria)
                        .addGap(104, 104, 104)
                        .addComponent(PrecioPizzaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelecSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombredelaPizzaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelecPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioPizzaOrdenes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescripcionpizzaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreciosActionPerformed

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        Ordenes ordenes;
        ordenes = new Ordenes(txtDescrip.getText(),txtNo.getText(), SelecSucursal.getSelectedItem().toString(), SelecPizza.getSelectedItem().toString());
        Listado.add(ordenes);
        MostarOrden();
    }//GEN-LAST:event_botoncrearActionPerformed

       public void MostarOrden(){
        String matriz2[][]= new String [Listado.size()][4];
        for (int i = 0; i < Listado.size(); i++) {
        matriz2 [i][0]= Listado.get(i).getNo();
        matriz2 [i][1] = Listado.get(i).getEspecialidad();
        matriz2 [i][2]= Listado.get(i).getDescrip();
        matriz2 [i][3] = Listado.get(i).getSucursal();
    }
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
         matriz2,
            new String [] {
                "No.", "Pizza", "Descripción", "Sucursal"
            }
        ));
    }
    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        index i = new index(Listado2,Listado);
        i.setVisible(true);
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void SelecPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecPizzaActionPerformed
        System.out.println("Select de la pizza: "+SelecPizza.getSelectedItem());
        for(int i=0;i<Listado2.size();i++){
            if(Listado2.get(i).getNombre().equals(SelecPizza.getSelectedItem())){
                txtDescrip.setText(Listado2.get(i).getDescripcion());
                txtPrecios.setText(Listado2.get(i).getPrecio());
            }
          
        }
    }//GEN-LAST:event_SelecPizzaActionPerformed

    private void SelecSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecSucursalActionPerformed
        
    }//GEN-LAST:event_SelecSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenesPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenesPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenesPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenesPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenesPizzas().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescripcionpizzaOrdenes;
    private javax.swing.JLabel NombrePizzeria;
    private javax.swing.JLabel NombredelaPizzaOrdenes;
    private javax.swing.JLabel PrecioPizzaOrdenes;
    private javax.swing.JLabel PrecioPizzaOrdenes1;
    private javax.swing.JComboBox<String> SelecPizza;
    private javax.swing.JComboBox<String> SelecSucursal;
    private javax.swing.JLabel SucursalOrdenes;
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtPrecios;
    // End of variables declaration//GEN-END:variables
}
